---
- hosts: k8s_workers
  collections:
  - community.general
  become: true
  tasks:
  - name: Set Hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Set up netplan
    template:
      src: templates/01-bond0.yaml.j2
      dest: /etc/netplan/01-bond0.yaml
      backup: yes
    register: bond0_netplan

  - name: Apply netplan
    command: netplan apply
    when: bond0_netplan.changed

  - name: Load br_netfilter module
    modprobe:
      name: br_netfilter
      state: present

  - name: Load overlay module
    modprobe:
      name: overlay
      state: present

  - name: Check if /etc/modules-load.d/containerd.conf exists
    stat:
      path: /etc/modules-load.d/containerd.conf
    register: containerd_mods

  - name: Create /etc/modules-load.d/containerd.conf
    copy:
      content: |
        overlay
        br_netfilter
      dest: /etc/modules-load.d/containerd.conf
    when: not containerd_mods.stat.exists
    
  - name: Check if /etc/sysctl.d/99-kubernetes-cri.conf exists
    stat:
      path: /etc/sysctl.d/99-kubernetes-cri.conf
    register: kubernetes_cri_sysctl

  - name: Create /etc/sysctl.d/99-kubernetes-cri.conf
    copy:
      content: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
    when: not kubernetes_cri_sysctl.stat.exists
    register: create_kubernetes_cri_sysctl

  - name: Apply sysctl settings
    command: sysctl --system
    when: create_kubernetes_cri_sysctl.changed

  - name: Update hostsfile
    replace:
      path: /etc/hosts
      regexp: '(\s+)ubuntu(\s+.*)?$'
      replace: '\1{{ inventory_hostname }}\2'

  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - containerd

  - name: Check if /etc/containerd/config.toml exists
    stat:
      path: /etc/containerd/config.toml
    register: containerd_config

  - name: Create /etc/containerd/config.toml and restart
    shell: |
      mkdir -p /etc/containerd &&
      containerd config default | tee /etc/containerd/config.toml &&
      systemctl restart containerd
    when: not containerd_config.stat.exists
    args:
      warn: false

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet=1.25.2-00 
        - kubeadm=1.25.2-00
        - kubectl=1.25.2-00
  
  - name: Hold kubelet
    dpkg_selections:
      name: kubelet
      selection: hold
  
  - name: Hold kubeadm
    dpkg_selections:
      name: kubeadm
      selection: hold

  - name: Hold kubectl
    dpkg_selections:
      name: kubectl
      selection: hold
  
  - name: Copy join command
    copy:
      src: joincommand
      dest: /tmp/join-command.sh
      mode: 0777
  
  - name: Check if kubelet is running
    command: pgrep kubelet
    register: kubelet_status

  - name: Join k8s cluster
    command: sh /tmp/join-command.sh
    ignore_errors: yes
    when: kubelet_status.rc != 0
